version: '3'

services:
  mysql:
    image: mysql:8.4.3
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - _IN_DOCKER=True
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
