apiVersion: apps/v1
kind: Deployment
metadata:
  name: videonet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: videonet
  template:
    metadata:
      labels:
        app: videonet
    spec:
      containers:
      - name: web
        image: alexisandradedev/videonet:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-secrets
              key: MYSQL_PASSWORD
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        - name: MYSQL_HOST # no modificar
          value: "mysql"
        - name: _IN_DOCKER # no modificar
          value: "True"
